version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.10-management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
        - ./rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
